preUpgradeChecker:                                                                                            
  jobEnabled: false
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: longhorn.example.com
      paths:
        - /
