apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.0
    helm:
      version: v3
      values: |
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
            - host: longhorn.example.com
              paths: 
                - /
        preUpgradeChecker:
          jobEnabled: false
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
