apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.0
    helm:
      version: v3
      valueFiles:                                                                                                   
        - $values/longhorn/values.yaml                                                                             
    - repoURL: https://github.com/7uu13/argocd.git                                                                    
      targetRevision: HEAD                                                                                            
      ref: values
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
